In [2]:
import os

import pandas as pd
import numpy as np

import sqlalchemy
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session
from sqlalchemy import create_engine

from flask import Flask, jsonify, render_template
from flask_sqlalchemy import SQLAlchemy

app = Flask(__name__)


#################################################
# Database Setup
#################################################

app.config["SQLALCHEMY_DATABASE_URI"] = "sqlite:///bellybutton.sqlite"
db = SQLAlchemy(app)

# reflect an existing database into a new model
Base = automap_base()
# reflect the tables
Base.prepare(db.engine, reflect=True)

# Save references to each table
Samples_Metadata = Base.classes.sample_metadata
Samples = Base.classes.samples

C:\Users\19143\Anaconda3\lib\site-packages\flask_sqlalchemy\__init__.py:835: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '

In [4]:
print(Samples_Metadata)

<class 'sqlalchemy.ext.automap.sample_metadata'>

In [5]:
# Use Pandas to perform the sql query
stmt = db.session.query(Samples).statement
df = pd.read_sql_query(stmt, db.session.bind)

In [7]:
df.head(11)

,otu_id,otu_label,940,941,943,944,945,946,947,948,...,1562,1563,1564,1572,1573,1574,1576,1577,1581,1601
0,1,Archaea;Euryarchaeota;Halobacteria;Halobacteri...,0,0,0,0,0,0,0,0.0,...,0,0,0,0,0,0,0,0,0,0
1,2,Archaea;Euryarchaeota;Halobacteria;Halobacteri...,0,0,0,0,0,0,0,0.0,...,0,0,0,0,0,0,0,0,0,0
2,3,Archaea;Euryarchaeota;Halobacteria;Halobacteri...,0,0,0,0,0,0,0,0.0,...,0,0,0,0,0,0,0,0,0,0
3,4,Archaea;Euryarchaeota;Methanobacteria;Methanob...,0,0,0,0,0,0,0,0.0,...,0,0,0,0,0,0,0,0,0,0
4,5,Archaea;Euryarchaeota;Methanobacteria;Methanob...,0,0,0,0,0,0,0,0.0,...,0,0,0,0,0,0,0,0,0,0
5,6,Archaea;Euryarchaeota;Methanobacteria;Methanob...,0,0,0,0,0,0,0,0.0,...,0,0,0,0,0,0,0,0,0,0
6,7,Bacteria,0,0,0,0,0,0,0,0.0,...,0,0,0,0,0,0,0,0,0,0
7,8,Bacteria,0,0,0,0,0,0,0,0.0,...,0,0,1,0,0,0,0,0,0,0
8,9,Bacteria,0,0,0,0,0,1,0,0.0,...,0,0,0,0,0,0,0,0,0,0
9,10,Bacteria,0,0,0,0,0,0,0,0.0,...,0,0,0,0,0,0,0,0,0,0
10,11,Bacteria,1,0,0,0,0,0,0,1.0,...,0,0,0,0,0,0,0,0,0,0

In [13]:
sample = "940"
sample_data = df.loc[df[sample] > 1, ["otu_id", "otu_label", sample]]
sample_data

      otu_id                                          otu_label  940
40        41                                           Bacteria   71
120      121                                           Bacteria    2
158      159                                           Bacteria    2
164      165                                           Bacteria   12
169      170                                           Bacteria    2
188      189                                           Bacteria   47
257      258                                           Bacteria    2
258      259                                           Bacteria    2
306      307                                           Bacteria    7
339      340                                           Bacteria    2
341      342                                           Bacteria    2
351      352                                           Bacteria   50
356      357                                           Bacteria    2
411      412                                           Bacteria    2
481      482                                           Bacteria  113
512      513                                           Bacteria    2
724      725  Bacteria;Actinobacteria;Actinobacteria;Actinom...    2
829      830  Bacteria;Actinobacteria;Actinobacteria;Actinom...   10
832      833  Bacteria;Actinobacteria;Actinobacteria;Actinom...    3
873      874  Bacteria;Actinobacteria;Actinobacteria;Actinom...   36
906      907  Bacteria;Actinobacteria;Actinobacteria;Actinom...    3
943      944  Bacteria;Actinobacteria;Actinobacteria;Actinom...   19
1166    1167  Bacteria;Bacteroidetes;Bacteroidia;Bacteroidal...  163
1168    1169  Bacteria;Bacteroidetes;Bacteroidia;Bacteroidal...    2
1188    1189  Bacteria;Bacteroidetes;Bacteroidia;Bacteroidal...   51
1192    1193  Bacteria;Bacteroidetes;Bacteroidia;Bacteroidal...    6
1207    1208  Bacteria;Bacteroidetes;Bacteroidia;Bacteroidal...    5
1231    1232  Bacteria;Bacteroidetes;Bacteroidia;Bacteroidal...    2
1273    1274  Bacteria;Bacteroidetes;Bacteroidia;Bacteroidal...    4
1313    1314  Bacteria;Bacteroidetes;Bacteroidia;Bacteroidal...    3
...      ...                                                ...  ...
2185    2186  Bacteria;Firmicutes;Clostridia;Clostridiales;I...    3
2187    2188  Bacteria;Firmicutes;Clostridia;Clostridiales;I...    2
2190    2191  Bacteria;Firmicutes;Clostridia;Clostridiales;I...   28
2234    2235  Bacteria;Firmicutes;Clostridia;Clostridiales;I...    2
2243    2244  Bacteria;Firmicutes;Clostridia;Clostridiales;I...   14
2246    2247  Bacteria;Firmicutes;Clostridia;Clostridiales;I...   11
2263    2264  Bacteria;Firmicutes;Clostridia;Clostridiales;I...   78
2274    2275  Bacteria;Firmicutes;Clostridia;Clostridiales;I...   22
2290    2291  Bacteria;Firmicutes;Clostridia;Clostridiales;I...    2
2317    2318  Bacteria;Firmicutes;Clostridia;Clostridiales;I...   40
2334    2335  Bacteria;Firmicutes;Clostridia;Clostridiales;I...    3
2341    2342  Bacteria;Firmicutes;Clostridia;Clostridiales;I...    2
2349    2350  Bacteria;Firmicutes;Clostridia;Clostridiales;I...    2
2395    2396  Bacteria;Firmicutes;Clostridia;Clostridiales;I...   11
2418    2419  Bacteria;Firmicutes;Clostridia;Clostridiales;I...   13
2474    2475  Bacteria;Firmicutes;Clostridia;Clostridiales;I...    2
2482    2483  Bacteria;Firmicutes;Clostridia;Clostridiales;I...    2
2490    2491  Bacteria;Firmicutes;Clostridia;Clostridiales;I...    2
2545    2546  Bacteria;Firmicutes;Clostridia;Clostridiales;I...    2
2570    2571  Bacteria;Firmicutes;Clostridia;Clostridiales;I...    2
2721    2722  Bacteria;Firmicutes;Clostridia;Clostridiales;I...    8
2736    2737  Bacteria;Firmicutes;Clostridia;Clostridiales;I...    4
2738    2739  Bacteria;Firmicutes;Clostridia;Clostridiales;I...    4
2781    2782  Bacteria;Firmicutes;Clostridia;Clostridiales;I...   12
2810    2811  Bacteria;Firmicutes;Clostridia;Clostridiales;I...   13
2858    2859  Bacteria;Firmicutes;Clostridia;Clostridiales;I...  126
2907    2908  Bacteria;Firmicutes;Clostridia;Clostridiales;P...    7
2935    2936  Bacteria;Firmicutes;Clostridia;Clostridiales;R...    3
2963    2964  Bacteria;Firmicutes;Clostridia;Clostridiales;V...   10
3449    3450  Bacteria;Proteobacteria;Epsilonproteobacteria;...   37

[80 rows x 3 columns]

In [16]:
# Sort by sample
sample_data.sort_values(by=sample, ascending=False, inplace=True)
sample_data

      otu_id                                          otu_label  940
1166    1167  Bacteria;Bacteroidetes;Bacteroidia;Bacteroidal...  163
2858    2859  Bacteria;Firmicutes;Clostridia;Clostridiales;I...  126
481      482                                           Bacteria  113
2263    2264  Bacteria;Firmicutes;Clostridia;Clostridiales;I...   78
40        41                                           Bacteria   71
1188    1189  Bacteria;Bacteroidetes;Bacteroidia;Bacteroidal...   51
351      352                                           Bacteria   50
188      189                                           Bacteria   47
2317    2318  Bacteria;Firmicutes;Clostridia;Clostridiales;I...   40
1976    1977       Bacteria;Firmicutes;Clostridia;Clostridiales   40
3449    3450  Bacteria;Proteobacteria;Epsilonproteobacteria;...   37
873      874  Bacteria;Actinobacteria;Actinobacteria;Actinom...   36
1958    1959                     Bacteria;Firmicutes;Clostridia   30
2190    2191  Bacteria;Firmicutes;Clostridia;Clostridiales;I...   28
1949    1950                     Bacteria;Firmicutes;Clostridia   25
2076    2077       Bacteria;Firmicutes;Clostridia;Clostridiales   23
2274    2275  Bacteria;Firmicutes;Clostridia;Clostridiales;I...   22
943      944  Bacteria;Actinobacteria;Actinobacteria;Actinom...   19
2183    2184  Bacteria;Firmicutes;Clostridia;Clostridiales;I...   19
2243    2244  Bacteria;Firmicutes;Clostridia;Clostridiales;I...   14
2418    2419  Bacteria;Firmicutes;Clostridia;Clostridiales;I...   13
2810    2811  Bacteria;Firmicutes;Clostridia;Clostridiales;I...   13
2023    2024       Bacteria;Firmicutes;Clostridia;Clostridiales   13
164      165                                           Bacteria   12
2781    2782  Bacteria;Firmicutes;Clostridia;Clostridiales;I...   12
2246    2247  Bacteria;Firmicutes;Clostridia;Clostridiales;I...   11
2010    2011       Bacteria;Firmicutes;Clostridia;Clostridiales   11
2395    2396  Bacteria;Firmicutes;Clostridia;Clostridiales;I...   11
829      830  Bacteria;Actinobacteria;Actinobacteria;Actinom...   10
2963    2964  Bacteria;Firmicutes;Clostridia;Clostridiales;V...   10
...      ...                                                ...  ...
258      259                                           Bacteria    2
512      513                                           Bacteria    2
169      170                                           Bacteria    2
724      725  Bacteria;Actinobacteria;Actinobacteria;Actinom...    2
2545    2546  Bacteria;Firmicutes;Clostridia;Clostridiales;I...    2
2290    2291  Bacteria;Firmicutes;Clostridia;Clostridiales;I...    2
2349    2350  Bacteria;Firmicutes;Clostridia;Clostridiales;I...    2
2570    2571  Bacteria;Firmicutes;Clostridia;Clostridiales;I...    2
158      159                                           Bacteria    2
1504    1505                                Bacteria;Firmicutes    2
2490    2491  Bacteria;Firmicutes;Clostridia;Clostridiales;I...    2
2474    2475  Bacteria;Firmicutes;Clostridia;Clostridiales;I...    2
2482    2483  Bacteria;Firmicutes;Clostridia;Clostridiales;I...    2
1168    1169  Bacteria;Bacteroidetes;Bacteroidia;Bacteroidal...    2
2109    2110       Bacteria;Firmicutes;Clostridia;Clostridiales    2
1231    1232  Bacteria;Bacteroidetes;Bacteroidia;Bacteroidal...    2
356      357                                           Bacteria    2
2187    2188  Bacteria;Firmicutes;Clostridia;Clostridiales;I...    2
257      258                                           Bacteria    2
2064    2065       Bacteria;Firmicutes;Clostridia;Clostridiales    2
120      121                                           Bacteria    2
1967    1968                     Bacteria;Firmicutes;Clostridia    2
339      340                                           Bacteria    2
2234    2235  Bacteria;Firmicutes;Clostridia;Clostridiales;I...    2
411      412                                           Bacteria    2
1502    1503                                Bacteria;Firmicutes    2
1497    1498                                Bacteria;Firmicutes    2
1496    1497                                Bacteria;Firmicutes    2
1959    1960                     Bacteria;Firmicutes;Clostridia    2
341      342                                           Bacteria    2

[80 rows x 3 columns]

In [ ]:
# Format the data to send as json
data = {
"otu_ids": sample_data.otu_id.values.tolist(),
"sample_values": sample_data[sample].values.tolist(),
"otu_labels": sample_data.otu_label.tolist(),
}
data